### PR TITLE
add windowed player support for clicked video thumbnails

### PR DESCRIPTION
**Pull request by sdetweil**
here is working player, using youtube api, dynamically inserting their javascript into MM

### CODE REVIEW

**Comment by cowboysdude** [comment]
WOW you've been busy :) Sorry I've been trying to work on another thing I have going on and that's not playing nice with MMM-voice either sooooooooo I put that away for a day or two then I'll go back to it..  I will focus on this now :)

**Comment by sdetweil** [comment]
Whatever. No rush. Just wanted to give u what I had. All kinds of ideas for
further work.

Have fun. Let me know if I can help with anything

**Comment by cowboysdude** [comment]
Thank you Sam!! Keep your ideas coming...... you've done a great job!!  :)  Thank you!   I have to fix an error in MMM-Recipe as it loads and perhaps that is the issue it's having with voice I'm not sure yet...  The whole entire project has been difficult as the data was difficult to work with....it's coming from the API in such bad shape it had to basically be rewritten in the node_helper to make is usable :)

**Comment by sdetweil** [comment]
I made a converter for Mykle to get his raw data into usable Json. Many api
designers clearly have never been data consumers!

**Comment by cowboysdude** [comment]
LOL  Well what I came up with works great AND it solves a problem for Mykle with his drink module as the data is identical......makes NO sense why they'd do that.....it's horrible.   I agree they are probably not data consumers.....just threw an api out there that is difficult to work with at best.

**Comment by cowboysdude** [comment]
How does it scroll?

**Comment by cowboysdude** [comment]
Sam this is pretty amazing stuff!!  You're right it's very simple but it works :)  I'm curious you said you had some other ideas......like to hear them :)

**Comment by sdetweil** [comment]
shuffle list
config for autoplay or not
highlighting the current playing,size/color of the selection rectangle
somehow rotate list to surface the playing icon
size of the player window

**Comment by sdetweil** [comment]
Have to look at status change, pause, and start a timer.  Video is
hidden/deletef on done/ended

**Comment by sdetweil** [comment]
Then call stopVideo , which cleans up for next play request

**Comment by sdetweil** [comment]
YT play replaces a named Div with the player element. stopVideo puts the
div back, and deletes the player

**Comment by cowboysdude** [comment]
OH ok that'll work! :)

**Pull request merged**
